import { useEffect, useState } from 'react';
import Layout from '../components/Layout';
import { api, formatDate } from '../utils/api';

const inputClass = 'w-full rounded-lg border border-gray-300 px-3 py-2 text-sm';
export default function AdminSetup() {
  const [setup,setSetup]=useState({departments:[],branches:[],shifts:[],rules:{}});
  const [holidays,setHolidays]=useState([]); const [error,setError]=useState('');
  const [department,setDepartment]=useState('');
  const [branch,setBranch]=useState({name:'',addressLine1:'',city:'',state:'',country:'India',pincode:'',latitude:'',longitude:'',allowedRadiusMeters:100});
  const [shift,setShift]=useState({name:'',startTime:'09:00',endTime:'18:00',graceMinutes:15,halfDayMinutes:240,fullDayMinutes:480,overtimeAfterMinutes:540,isSplit:false,slots:[]});
  const [holiday,setHoliday]=useState({name:'',holidayDate:'',branchId:'',description:''});
  const load=async()=>{try{const [s,h]=await Promise.all([api.getAdminSetup(),api.getHolidays()]);setSetup(s);setHolidays(h);}catch(err){setError(err.message);}};
  useEffect(()=>{load();},[]);
  const run=async(action,reset)=>{setError('');try{await action();reset?.();await load();}catch(err){setError(err.message);}};
  const addSlot=()=>setShift({...shift,isSplit:true,slots:[...shift.slots,{startTime:'09:00',endTime:'13:00'}]});
  return <Layout><div className="mb-6"><h1 className="text-2xl font-bold">Attendance Setup</h1><p className="text-sm text-gray-500">Branches, shifts, rules and holidays.</p></div>
    {error&&<div className="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <div className="grid gap-6 lg:grid-cols-2">
      <section className="rounded-xl bg-white p-5 shadow-sm"><h2 className="mb-3 font-semibold">Departments</h2><div className="flex gap-2"><input value={department} onChange={e=>setDepartment(e.target.value)} placeholder="Department name" className={inputClass}/><button onClick={()=>run(()=>api.createDepartment({name:department}),()=>setDepartment(''))} className="rounded-lg bg-primary-600 px-4 text-sm text-white">Add</button></div><div className="mt-3 flex flex-wrap gap-2">{setup.departments.map(d=><span key={d.id} className="rounded-full bg-gray-100 px-3 py-1 text-xs">{d.name}</span>)}</div></section>
      <section className="rounded-xl bg-white p-5 shadow-sm"><h2 className="mb-3 font-semibold">Attendance Rules</h2><label className="text-xs text-gray-600">Late grace occurrences per month</label><div className="mt-1 flex gap-2"><input type="number" min="0" value={setup.rules?.late_grace_occurrences??0} onChange={e=>setSetup({...setup,rules:{...setup.rules,late_grace_occurrences:e.target.value}})} className={inputClass}/><button onClick={()=>run(()=>api.updateRules({lateGraceOccurrences:Number(setup.rules.late_grace_occurrences)}))} className="rounded-lg bg-primary-600 px-4 text-sm text-white">Save</button></div></section>
      <section className="rounded-xl bg-white p-5 shadow-sm lg:col-span-2"><h2 className="mb-3 font-semibold">New Branch</h2><div className="grid gap-3 md:grid-cols-4">{['name','addressLine1','city','state','country','pincode','latitude','longitude','allowedRadiusMeters'].map(key=><label key={key}><span className="mb-1 block text-xs capitalize text-gray-600">{key.replace(/([A-Z])/g,' $1')}</span><input type={['latitude','longitude','allowedRadiusMeters'].includes(key)?'number':'text'} value={branch[key]} onChange={e=>setBranch({...branch,[key]:e.target.value})} className={inputClass}/></label>)}</div><button onClick={()=>run(()=>api.createBranch(branch),()=>setBranch({...branch,name:'',addressLine1:'',city:'',state:'',pincode:'',latitude:'',longitude:''}))} className="mt-3 rounded-lg bg-primary-600 px-4 py-2 text-sm text-white">Create Branch</button><div className="mt-4 text-sm text-gray-600">{setup.branches.map(b=><div key={b.id}>{b.name} · {b.city} · {b.allowed_radius_meters}m radius</div>)}</div></section>
      <section className="rounded-xl bg-white p-5 shadow-sm lg:col-span-2"><h2 className="mb-3 font-semibold">New Shift</h2><div className="grid gap-3 md:grid-cols-4">{['name','startTime','endTime','graceMinutes','halfDayMinutes','fullDayMinutes','overtimeAfterMinutes'].map(key=><label key={key}><span className="mb-1 block text-xs text-gray-600">{key.replace(/([A-Z])/g,' $1')}</span><input type={key.includes('Time')?'time':key==='name'?'text':'number'} value={shift[key]} onChange={e=>setShift({...shift,[key]:e.target.value})} className={inputClass}/></label>)}</div><div className="mt-3 space-y-2">{shift.slots.map((slot,index)=><div className="flex gap-2" key={index}><input type="time" value={slot.startTime} onChange={e=>setShift({...shift,slots:shift.slots.map((s,i)=>i===index?{...s,startTime:e.target.value}:s)})} className={inputClass}/><input type="time" value={slot.endTime} onChange={e=>setShift({...shift,slots:shift.slots.map((s,i)=>i===index?{...s,endTime:e.target.value}:s)})} className={inputClass}/></div>)}</div><div className="mt-3 flex gap-2"><button onClick={addSlot} className="rounded-lg border px-4 py-2 text-sm">Add split slot</button><button onClick={()=>run(()=>api.createShift(shift),()=>setShift({...shift,name:'',slots:[],isSplit:false}))} className="rounded-lg bg-primary-600 px-4 py-2 text-sm text-white">Create Shift</button></div><div className="mt-4 text-sm text-gray-600">{setup.shifts.map(s=><div key={s.id}>{s.name} · {String(s.start_time).slice(0,5)}-{String(s.end_time).slice(0,5)} {s.is_split?'(split shift)':''}</div>)}</div></section>
      <section className="rounded-xl bg-white p-5 shadow-sm lg:col-span-2"><h2 className="mb-3 font-semibold">Holidays</h2><div className="grid gap-3 md:grid-cols-4"><input placeholder="Holiday name" value={holiday.name} onChange={e=>setHoliday({...holiday,name:e.target.value})} className={inputClass}/><input type="date" value={holiday.holidayDate} onChange={e=>setHoliday({...holiday,holidayDate:e.target.value})} className={inputClass}/><select value={holiday.branchId} onChange={e=>setHoliday({...holiday,branchId:e.target.value})} className={inputClass}><option value="">All branches</option>{setup.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><button onClick={()=>run(()=>api.createHoliday(holiday),()=>setHoliday({name:'',holidayDate:'',branchId:'',description:''}))} className="rounded-lg bg-primary-600 px-4 py-2 text-sm text-white">Add Holiday</button></div><div className="mt-4 divide-y">{holidays.map(h=><div key={h.id} className="flex items-center justify-between py-3 text-sm"><span><b>{h.name}</b> · {formatDate(h.holiday_date)} · {h.branch_name||'All branches'}</span><button onClick={()=>run(()=>api.deleteHoliday(h.id))} className="text-red-600">Delete</button></div>)}</div></section>
    </div>
  </Layout>;
}
